# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [ ]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates a dim x dim array of integers between 0 and 10.
    """
    matrix = np.random.randint(10, size=(dim, dim))

    return matrix

def permutations(dim):
    """
    The function creates a list of all permutations of numbers from 1 to dim.
    """

    return list(itertools.permutations(range(1, dim + 1)))

def calculate_product(matrix, perm):
    """
    The function computes the product of the elements of a matrix for a given permutation.
    """
    product = 1
    
    for i in range(len(perm)):
        product *= matrix[i][perm[i] - 1]

    return product

def calculate_determinant(matrix):
    """
    The function calculates the determinant of a matrix using the permutation rule.
    """
    dim = len(matrix)
    perms = permutations(dim)
    determinant = 0
    for perm in perms:
        invert = 0

        for i in range(dim):

            for j in range(i + 1, dim):

                if perm[i] > perm[j]:
                    invert += 1

        sign = (-1) ** invert
        product = calculate_product(matrix, perm)
        determinant += sign * product
    return determinant

dim = int(input("Enter the dimensionality of the matrix = "))

if dim > 0:

    matrix = random_matrix(dim)
    print("Your matrix:")
    print(matrix)

    ur_determinant = calculate_determinant(matrix)
    
    linalg_determinant = np.linalg.det(matrix)

    print("Determinant of your matrix (custom function):", ur_determinant)
    print("Determinant with np.linalg.det:", linalg_determinant)

else:
    print("Enter an integer greater than 0.")

input("Press Enter to close this program...")

[[4 6 5]
 [7 1 7]
 [0 9 9]]
